### ISSUE TITLE
Positioning of Player should be random

### ISSUE THREAD

**Issue by RudiKlassen-zz** [adessoSE/BrainySnake#28]
Actually the initial positions of the agents in match are fixed (also the orientations). 

## acceptance criteria
* Initial position is random in level
* Initial orientation ist random 
* Agent should not be blocked by level or barriers (no blocking elements in playerview)

**Comment by dariobraun** [comment]
@AlexanderBrockmann While working on #30 I came across the issue of checking if a Snake and a barrier overlap. Makes more sense for you to handle it in this issue, right?

**Comment by AlexanderBrockmann** [comment]
@dariobraun Actually there is already a method for this purpose in Level. It's called checkColision and returns a true boolean if the given Point2D is listed in levelWalls or barriers.
Although it isn't necessary to check if a barrier is overlapping a snake because the snake should be created afterwards.
